# Generated by Django 3.0.8 on 2020-07-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Turma', '0001_initial'),
        ('Professor', '0001_initial'),
        ('SalaDeAula', '0001_initial'),
        ('Disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotDeHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField(unique=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disciplina.Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professor.Professor')),
                ('sala_de_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalaDeAula.SalaDeAula')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turma.Turma')),
            ],
            options={
                'verbose_name_plural': 'Slots de horario',
            },
        ),
    ]
