# Generated by Django 3.0.8 on 2020-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaDeAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('Sala regular', 'Sala regular'), ('Laboratório', 'Laboratório'), ('Audiovisual', 'Audiovisual'), ('Auditório', 'Auditório'), ('Miniauditório', 'Miniauditório')], max_length=15)),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Salas de aula',
            },
        ),
    ]
