# Generated by Django 3.0.8 on 2020-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=15)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'turmas',
            },
        ),
    ]
