# Generated by Django 3.0.8 on 2020-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=90)),
                ('matricula', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'professores',
            },
        ),
    ]
